name: plugin-test # the plugins name as it should appear in the plugin list /pl
version: 1.0 # the plugin's version
main: dev.andrewpecha.spigottest.Main
api-version: 1.18
commands:
  kit:
    description: Give character a diamond and 20 bricks!
    usage: /kit
  move:
    description: Move Player +100 x
    usage: /move
  choochoo:
    description: Lay Mine Tracks FAST
    usage: /choochoo
  stairs:
    description: Blocks go brrrrr
    usage: /stairs